export enum TableNames {
    USERS = 'users',
    PRODUCTS = 'products',
    FILES = 'files',
    PROFILES = 'profiles',
    SESSIONS = 'sessions',
    VERIFICATIONS = 'verifications',
    AUDITS = 'audits',
    CHECKINS = "checkins",
    REVIEWS = "reviews",
    RATINGS = "ratings",
    ACTIVITIES = "activities",
    LINKED_ACCOUNTS = "linkedaccounts",
    FILE_MANAGER = "filemanager",
    AUDIT_LOGS = "auditlogs",
    PAYMENTS = "payments",
    USER_KYC = "userkyc",
    PAYMENT_TRANSACTIONS = "paymenttransactions",
    TRANSACTIONS = "transactions",
    CERTIFICATES = "certificates",
    DOCUMENTS = "documents",
    CONTACT_MESSAGES = 'contact_messages',
    NEWSLETTER_SUBSCRIPTIONS = 'newsletter_subscriptions',
    ROLES = 'roles',
    PERMISSIONS = 'permissions',
    ROLE_PERMISSIONS = 'role_permissions',
    USER_ROLES = 'user_roles',
    // Wallet system tables
    CURRENCIES = 'currencies',
    WALLETS = 'wallets',
    WALLET_ACCOUNTS = 'wallet_accounts',
}